name: gym
description: My Gym App

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  analyzer: ^0.38.5
  analyzer_plugin: ^0.2.1
  json_serializable: ^3.2.3
  path_provider: ^1.5.1
  connectivity: ^0.4.6+2
  dio: ^3.0.8
  equatable: ^0.4.0
  dartz: ^0.8.6
  shared_preferences: ^0.5.6
  rxdart: ^0.23.1
  toast: ^0.1.5
  flux_validator_dart: ^1.0.3
  moor_flutter: ^2.0.0
  permission: ^0.1.5
  vibration: ^1.2.2
  expandable: ^3.0.1
  url_launcher: ^5.4.1
  provider: ^3.0.0+1
  font_awesome_flutter: ^8.2.0
  flutter_flip_view: ^1.0.3
  flutter_cache_manager: ^1.1.3
  cached_network_image: ^2.0.0
  fluttertoast: ^4.0.1
  bubble_bottom_bar: ^1.2.0
  carousel_slider: ^2.2.1
  sliding_up_panel: ^1.0.0
  simple_animations: ^1.3.3
  sticky_headers: ^0.1.7


  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  moor_generator: ^2.2.0
  build_runner:
  test:
  test_core:

dependency_overrides:
  analyzer: '0.39.14'

flutter:
  uses-material-design: true

  assets:
    - lang/pt_BR.json
    - lang/en_US.json
    - assets/img/
    - assets/font/

  fonts:
    - family: OpenSans-Bold
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
